baseURL: https://larmic.de
languageCode: de
title: larmic.de
theme: "hugo-hero-theme"

enableRobotsTXT: true

menu:
  main:
    - name: Videos
      url: "/videos/"
      weight: 3
    - name: Workshops
      url: "/workshops/"
      weight: 2
    - name: Ãœber mich
      url: "/about/"
      weight: 1

params:
  env: production

  favicon: "/favicon.ico"
  favicon16x16: "/favicon16x16.png"
  favicon32x32: "/favicon32x32.png"

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  youtube:
    disabled: false
    privacyEnhanced: true
